name: Trigger Entity Kaggle Notebook

on:
  push:
    paths:
      - 'entity-data.dvc'  # Adjust this pattern to match your .dvc files

jobs:
  trigger_kaggle_notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.10.6

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install kaggle

      - name: Trigger Kaggle notebook via API
        env:
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
        run: |
          kaggle kernels push -p entity
